import { Invoice } from "../../types";

export const mockInvoices: Invoice[] = [
  {
    id: 1,
    invoiceNumber: "INV-1001",
    customer: "John Doe",
    amount: 250,
    date: "2025-01-05",
    dueDate: "2025-01-15",
    status: "Paid",
    description: "Web design services",
    items: [
      { item: "Website mockup", qty: 1, price: 150 },
      { item: "Revisions", qty: 2, price: 50 },
    ],
  },
  {
    id: 2,
    invoiceNumber: "INV-1002",
    customer: "Alice Smith",
    amount: 120,
    date: "2025-01-06",
    dueDate: "2025-01-16",
    status: "Unpaid",
    description: "Consultation session",
    items: [{ item: "Consultation", qty: 2, price: 60 }],
  },
  {
    id: 3,
    invoiceNumber: "INV-1003",
    customer: "Bob Johnson",
    amount: 430,
    date: "2025-01-07",
    dueDate: "2025-01-17",
    status: "Overdue",
    description: "Office hardware supply",
    items: [
      { item: "Laptop", qty: 1, price: 300 },
      { item: "Keyboard", qty: 2, price: 40 },
      { item: "Mouse", qty: 2, price: 25 },
    ],
  },
  {
    id: 4,
    invoiceNumber: "INV-1004",
    customer: "Emma Wilson",
    amount: 180,
    date: "2025-01-08",
    dueDate: "2025-01-18",
    status: "Paid",
    description: "Logo design",
    items: [{ item: "Logo design", qty: 1, price: 180 }],
  },
  {
    id: 5,
    invoiceNumber: "INV-1005",
    customer: "Michael Brown",
    amount: 320,
    date: "2025-01-09",
    dueDate: "2025-01-19",
    status: "Unpaid",
    description: "Mobile app UI",
    items: [{ item: "UI screens", qty: 8, price: 40 }],
  },
  {
    id: 6,
    invoiceNumber: "INV-1006",
    customer: "Sophia Taylor",
    amount: 90,
    date: "2025-01-10",
    dueDate: "2025-01-20",
    status: "Paid",
    description: "Content writing",
    items: [{ item: "Blog article", qty: 3, price: 30 }],
  },
  {
    id: 7,
    invoiceNumber: "INV-1007",
    customer: "Daniel Anderson",
    amount: 600,
    date: "2025-01-11",
    dueDate: "2025-01-21",
    status: "Unpaid",
    description: "Backend API development",
    items: [{ item: "API module", qty: 6, price: 100 }],
  },
  {
    id: 8,
    invoiceNumber: "INV-1008",
    customer: "Olivia Martinez",
    amount: 140,
    date: "2025-01-12",
    dueDate: "2025-01-22",
    status: "Paid",
    description: "SEO optimization",
    items: [{ item: "SEO audit", qty: 1, price: 140 }],
  },
  {
    id: 9,
    invoiceNumber: "INV-1009",
    customer: "James Thomas",
    amount: 75,
    date: "2025-01-13",
    dueDate: "2025-01-23",
    status: "Overdue",
    description: "Bug fixes",
    items: [{ item: "Bug fix", qty: 3, price: 25 }],
  },
  {
    id: 10,
    invoiceNumber: "INV-1010",
    customer: "Isabella Moore",
    amount: 500,
    date: "2025-01-14",
    dueDate: "2025-01-24",
    status: "Paid",
    description: "E-commerce setup",
    items: [
      { item: "Product setup", qty: 10, price: 30 },
      { item: "Payment integration", qty: 1, price: 200 },
    ],
  },

  // --- continuing pattern for realism ---
  ...Array.from({ length: 40 }, (_, i) => {
    const id = i + 11;
    return {
      id,
      invoiceNumber: `INV-${1000 + id}`,
      customer: `Customer ${id}`,
      amount: 50 + (id % 10) * 45,
      date: `2025-02-${String((id % 28) + 1).padStart(2, "0")}`,
      dueDate: `2025-02-${String((id % 28) + 8).padStart(2, "0")}`,
      status: (["Paid", "Unpaid", "Overdue"] as const)[id % 3],
      description: "General service charge",
      items: [
        {
          item: `Service ${id}`,
          qty: (id % 5) + 1,
          price: 45,
        },
      ],
    } satisfies Invoice;
  }),
];
