/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/auth/route'
import { Route as PublicBlogsIndexRouteImport } from './routes/_public/blogs/index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public/about/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as PublicAuthRegisterIndexRouteImport } from './routes/_public/auth/register/index'
import { Route as PublicAuthLoginIndexRouteImport } from './routes/_public/auth/login/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogsIndexRoute = PublicBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicAuthRegisterIndexRoute = PublicAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthLoginIndexRoute = PublicAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof PublicAuthRouteRouteWithChildren
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof PublicIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/blogs': typeof PublicBlogsIndexRoute
  '/auth/login': typeof PublicAuthLoginIndexRoute
  '/auth/register': typeof PublicAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof PublicAuthRouteRouteWithChildren
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof PublicIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/blogs': typeof PublicBlogsIndexRoute
  '/auth/login': typeof PublicAuthLoginIndexRoute
  '/auth/register': typeof PublicAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/auth': typeof PublicAuthRouteRouteWithChildren
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/blogs/': typeof PublicBlogsIndexRoute
  '/_public/auth/login/': typeof PublicAuthLoginIndexRoute
  '/_public/auth/register/': typeof PublicAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/'
    | '/invoices'
    | '/settings'
    | '/about'
    | '/blogs'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/'
    | '/invoices'
    | '/settings'
    | '/about'
    | '/blogs'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_public/auth'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/_public/'
    | '/_authenticated/invoices/'
    | '/_authenticated/settings/'
    | '/_public/about/'
    | '/_public/blogs/'
    | '/_public/auth/login/'
    | '/_public/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blogs/': {
      id: '/_public/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof PublicBlogsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/auth/register/': {
      id: '/_public/auth/register/'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterIndexRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/auth/login/': {
      id: '/_public/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginIndexRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicAuthRouteRouteChildren {
  PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
  PublicAuthRegisterIndexRoute: typeof PublicAuthRegisterIndexRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute,
  PublicAuthRegisterIndexRoute: PublicAuthRegisterIndexRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicBlogsIndexRoute: typeof PublicBlogsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicBlogsIndexRoute: PublicBlogsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
