/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as PublicBlogsIndexRouteImport } from './routes/_public/blogs/index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public/about/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as PublicAuthRegisterIndexRouteImport } from './routes/_public/auth/register/index'
import { Route as PublicAuthLoginIndexRouteImport } from './routes/_public/auth/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBlogsIndexRoute = PublicBlogsIndexRouteImport.update({
  id: '/_public/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/_public/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/_authenticated/settings/',
    path: '/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/_authenticated/invoices/',
    path: '/invoices/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicAuthRegisterIndexRoute = PublicAuthRegisterIndexRouteImport.update({
  id: '/_public/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthLoginIndexRoute = PublicAuthLoginIndexRouteImport.update({
  id: '/_public/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/blogs': typeof PublicBlogsIndexRoute
  '/auth/login': typeof PublicAuthLoginIndexRoute
  '/auth/register': typeof PublicAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/about': typeof PublicAboutIndexRoute
  '/blogs': typeof PublicBlogsIndexRoute
  '/auth/login': typeof PublicAuthLoginIndexRoute
  '/auth/register': typeof PublicAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/blogs/': typeof PublicBlogsIndexRoute
  '/_public/auth/login/': typeof PublicAuthLoginIndexRoute
  '/_public/auth/register/': typeof PublicAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/invoices'
    | '/settings'
    | '/about'
    | '/blogs'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/invoices'
    | '/settings'
    | '/about'
    | '/blogs'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/_authenticated/invoices/'
    | '/_authenticated/settings/'
    | '/_public/about/'
    | '/_public/blogs/'
    | '/_public/auth/login/'
    | '/_public/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicBlogsIndexRoute: typeof PublicBlogsIndexRoute
  PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
  PublicAuthRegisterIndexRoute: typeof PublicAuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/blogs/': {
      id: '/_public/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof PublicBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/register/': {
      id: '/_public/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/login/': {
      id: '/_public/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicBlogsIndexRoute: PublicBlogsIndexRoute,
  PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute,
  PublicAuthRegisterIndexRoute: PublicAuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
